---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ["private_network", { ip: "192.168.33.10" }]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: pizza::default
    attributes:
      pizza:
        consul:
          key_dir: "some/secret/key/value/pairs"
        database_url: "adapter://user:password@host:3306/database"
        deploy_to: /home/user/application
        elasticsearch_host: "127.0.0.1"
        repository: "git@github.com:user/repo.git"
        secret_key_base: veryverysecretkey
        ssh_key: "DO_YOU_THINK_I_AM_THAT_STUPID_TO_PUT_SSH_KEY_HERE"
        username: user
